export const ADD_TO_FAVORITE_LIST = 'ADD_TO_FAVORITE_LIST'
export const REMOVE_TO_FAVORITE_LIST = 'REMOVE_TO_FAVORITE_LIST'


export const FETCH_DATA_FAVORITE_REQUEST = 'FETCH_DATA_FAVORITE_REQUEST'
export const FETCH_DATA_FAVORITE_SUCCESS = 'FETCH_DATA_FAVORITE_SUCCESS'
export const FETCH_DATA_FAVORITE_FAILURE = 'FETCH_DATA_FAVORITE_FAILURE'

export const FETCH_DATA_FAVORITE_CURRENT_WEATHER_SAGA = 'FETCH_DATA_FAVORITE_CURRENT_WEATHER_SAGA'
