
// WEB API
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE'

//DEFULT
export const SET_IS_LAODED_FIRST_TIME='SET_IS_LAODED_FIRST_TIME'

//SEARCH BAR
export const SET_DATA_SEARCH='SET_DATA_SEARCH'

// SEARCH BY GEO SAGA

export const SEARCH_GEO_SAGA ='SEARCH_GEO_SAGA'

//SET SELECTED DATA INDEX
export const SET_SELECTED_DATA_INDEX = 'SET_SELECTED_DATA_INDEX'


//SAGA
export const FETCH_DATA_WEATHER_NEXT_FIVE_DAYS_SAGA = 'FETCH_DATA_WEATHER_NEXT_FIVE_DAYS_SAGA'
export const FETCH_DATA_FOR_AUTO_COMPLETION_SAGA = 'FETCH_DATA_FOR_AUTO_COMPLETION_SAGA'
export const FETCH_DATA_CURRENT_WEATHER_SAGA = 'FETCH_DATA_CURRENT_WEATHER_SAGA'
export const FETCH_DEFAULT_SAGA='FETCH_DEFAULT_SAGA'
